import colorama
from colorama import Fore, Back, Style
import requests
import os
import time
from os import name,system
def urlme(x):
    #URLpred = "https://raw.githubusercontent.com/lorxstudios/lsm/main/main.py"
    URL = x
    response = requests.get(URL)
    data = response.text
    return(data)
def clear():
 
    # for windows
    if name == 'nt':
        _ = system('cls')
 
    # for mac and linux(here, os.name is 'posix')
    else:
        _ = system('clear')
print("-------------------------------")
print("Empezando actualización")
print("")
print("")
print("")
print("")
print("")
print("")
print("- Descargando datos desde el GitHub de Lorx")
print("-------------------------------")
clear()
print("-------------------------------")
print("Instalando actualización")
print("")
print("")
print("")
print("")
print("")
print("")
print("- Actualizando definiciones.")
print("-------------------------------")
defs = open("defs.py", "w")
defs.write(urlme("https://raw.githubusercontent.com/lorxstudios/lsm/main/defs.py"))
defs.close()
print("-------------------------------")
print("Instalando actualización")
print("")
print("")
print("")
print("")
print("")
print("")
print("- Base de definiciones actualizada!")
print("-------------------------------")
time.sleep(0.5)
print("-------------------------------")
print("Instalando actualización")
print("")
print("")
print("")
print("")
print("")
print("")
print("- Actualizando Launcher.")
print("-------------------------------")
launch = open("launcher.py", "w")
launch.write(urlme("https://raw.githubusercontent.com/lorxstudios/lsm/main/launcher.py"))
launch.close()
print("-------------------------------")
print("Instalando actualización")
print("")
print("")
print("")
print("")
print("")
print("")
print("- Launcher actualizado!")
print("-------------------------------")
time.sleep(0.5)
print("-------------------------------")
print("Instalando actualización")
print("")
print("")
print("")
print("")
print("")
print("")
print("- Actualizando LSMe.")
print("-------------------------------")
launch = open("main.py", "w")
launch.write(urlme("https://raw.githubusercontent.com/lorxstudios/lsm/main/main.py"))
launch.close()
time.sleep(0.5)
print("-------------------------------")
print("Finalizando actualización")
print("")
print("")
print("")
print("")
print("")
print("")
print("- Comprobación")
print("-------------------------------")
time.sleep(0.5)
print("-------------------------------")
print("Comprobando actualización")
print("")
print("")
print("")
print("")
print("")
print("")
print("- Comprobación de los archivos")
print("-------------------------------")
lsme = open("main.py", "r").read()
launch = open("launcher.py", "r").read()
defs = open("defs.py", "r").read()
if lsme == urlme("https://raw.githubusercontent.com/lorxstudios/lsm/main/main.py"):
    lsme = "True"
else:
    lsme = "False"
if launch == urlme("https://raw.githubusercontent.com/lorxstudios/lsm/main/launcher.py"):
    launch = "True"
else:
    launch = "False"
if defs == urlme("https://raw.githubusercontent.com/lorxstudios/lsm/main/defs.py"):
    defs = "True"
else:
    defs = "False"
print("-------------------------------")
print("Resultados actualización")
print("")
print("")
print("")
print("")
print("")
print("")
print("- Comprobación de los archivos, resultados:")
print("LSMe:" + lsme)
print("Launcher:"+launch)
print("Defs:"+defs)
if launch == "False" or lsme == "False" or defs == "False":
    print("Uno o más resultados han sido incorrectamente instalados, por favor, procede a la actualización manual de nuestro GitHub, lorxstudios.")
    exit()
else:
    print("Todo se ha instalado satisfactoriamente, iniciando el Launcher de nuevo.")
    time.sleep(1)
    print("Gracias por confiar en Lorx.")
    time.sleep(1)
    clear()
    print("Volviendo en 5")
    time.sleep(1)
    print("Volviendo en 4")
    time.sleep(1)
    print("Volviendo en 3")
    time.sleep(1)
    print("Volviendo en 2")
    time.sleep(1)
    print("Volviendo en 1")
    time.sleep(1)
    print("Volviendo.......")
    time.sleep(0.1)
    clear()
    os.system("python3 launcher.py")
print("-------------------------------")
